dist: bionic
language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
python:
  - "2.7"

matrix:
  sudo: true
  fast_finish: true

env:
  matrix:
    - PAM_VERSION=1.x
    - PAM_VERSION=2.x

before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt

install:
  - bin/buildout -N -t 3 code-analysis:return-status-codes=True annotate -c buildout-pam-$PAM_VERSION.cfg
  - bin/buildout -N -t 3 code-analysis:return-status-codes=True -c buildout-pam-$PAM_VERSION.cfg

script:
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test --all
  - bin/sphinxbuilder
after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - bin/pip install -q coveralls
  - bin/coveralls
notifications:
  email:
    - mlarreategi@codesyntax.com
