dist: bionic
language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
python:
  - "2.7"
matrix:
  sudo: true
  fast_finish: true

env:
  matrix:
    - PAM_VERSION=1.x
    - PAM_VERSION=2.x

before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt

install:
  - sed -ie "s#pam-x.x.x.cfg#buildout-pam-$PAM_VERSION.cfg#" travis.cfg
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads

  script:
  - bin/code-analysis
  - bin/test --all
  - bin/sphinxbuilder
after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - bin/pip install -q coveralls
  - bin/coveralls
notifications:
  email:
    - mlarreategi@codesyntax.com
